### ISSUE TITLE
Publish on RubyGems

### ISSUE THREAD

**Issue by q231950** [xing/crep#14]
Publish Crep on [rubygems.org](http://guides.rubygems.org/publishing/).

**Comment by JoeSSS** [comment]
Done :tada: https://rubygems.org/gems/crep 

Please register at https://rubygems.org/sign_up and I will add you to owners

**Comment by BasThomas** [comment]
-> https://rubygems.org/profiles/basthomas

**Comment by JoeSSS** [comment]
Added!

**Comment by BasThomas** [comment]
Ah, do you want to add this in the Readme somewhere? Just to make people aware 👍.

**Comment by q231950** [comment]
Nice @JoeSSS 🎉 

I am https://rubygems.org/profiles/q231950

**Comment by JoeSSS** [comment]
@q231950 added! we already have 91 downloads there :)

**Comment by BasThomas** [comment]
> Ah, do you want to add this in the Readme somewhere?

I've updated the `Install` page of the wiki.

https://github.com/xing/crep/wiki/Install

**Comment by JoeSSS** [comment]
Beautiful, thanks
