### ISSUE TITLE
Add a logo!

### ISSUE THREAD

**Issue by BasThomas** [xing/crep#29]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Crazy idea - what about actually choosing this drawing as the logo (as-is)? 😮

**Comment by JoeSSS** [comment]
@BasThomas  +1 :)

**Comment by q231950** [comment]
The drawing hand would probably be ok ☺️

**Comment by q231950** [comment]
What about add temporary logo? https://github.com/xing/crep/tree/add_logo

**Comment by BasThomas** [comment]
Lovely. Go for it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by q231950** [comment]
I vote for Crep on the beach 🦀

**Comment by q231950** [comment]
@JoeSSS @dhartwich1991 are you fine with natural Crep?

**Comment by dhartwich1991** [comment]
@q231950 natural Crep = best Crep
