### ISSUE TITLE
Add colourful output for logs.

### ISSUE THREAD

**Issue by dhartwich1991** [xing/crep#44]
Nowadays shells support colorful output.
It makes it the output much more readable and easily distinguishable if it's an error or just a warning, or a debug log.

**Comment by BasThomas** [comment]
Where do you suggest we add these? Just to make sure, we already support colorization of output, like [here](https://github.com/xing/crep/blob/master/lib/crep/crash_controller.rb#L31).

**Comment by q231950** [comment]
@dhartwich1991 isn’t this solved by the latest colourful pr of yours?

**Comment by dhartwich1991** [comment]
@q231950 I wasn't sure if we should close it already? There are still some places that use `puts` especially the output of the top5 crashes. But I'm not sure if it even should be more colourful?

**Comment by BasThomas** [comment]
I think we can close it for now. We have the needed support for it now, and can always improve later. 👍
