### ISSUE TITLE
Release the Beast v1.0.0

### ISSUE THREAD

**Issue by q231950** [xing/crep#80]
When I look at our [milestones](https://github.com/xing/crep/milestones) and compare to our [releases](https://github.com/xing/crep/releases) it doesn't add up 😉

I am proposing to release the `v1.0.0` now, of course modifying the change log accordingly.

**Comment by q231950** [comment]
I had a look at http://www.rubydoc.info/gems/crep which made me think @BasThomas @jamuc @dhartwich1991 @JoeSSS. We should release a new version with the current state. The v0.1.0 is too far off. I think it's time, what do you think, should I just go for it?

**Comment by BasThomas** [comment]
Go for it; it’s “production” ready after all 😃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jamuc** [comment]
+1 +1 +1 +1 +1

**Comment by q231950** [comment]
[It's out](https://twitter.com/q231950/status/980736929342935040) 🎉

@jamuc, what's your twitter handle?

**Comment by jamuc** [comment]
@q231950 Would you believe it's @jamuc? I try to be consistent across platforms

**Comment by q231950** [comment]
That makes absolutely sense @jamuc.
